name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f workflow/requirements.txt ]; then pip install -r workflow/requirements.txt; fi
      - name: Apply template and tag
        run: |
          python workflow/apply_template.py
      # Add code to create git tag and pass tag to docker image
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: subuwithdocker/mlflow:latest